### PR TITLE
Commits to master weekly report

### PR DESCRIPTION
**Pull request by aerickson14**
Added the option that when a repo is not specified it will generate a report for all active repos and will report on commits made in the last 7 days.

### CODE REVIEW

**Comment by nealsanche** [comment]
This looks fine. Are you sure this is what Paul wanted? It seems like it'd produce a LOT of output. What would this be used for? Is it just to look for people who are committing directly to master all the time?

**Comment by aerickson14** [comment]
It's not terrible in terms of the output. The worst offenders are the single projects, and if a project hasn't been worked on in the past 7 days it is not included in the results.

Paul mentioned he wanted a way to run a report on all repos (without having to specifically type in or remember repository names) who have commits to master within the last 7 days.

**Comment by nealsanche** [comment]
So I wonder if he just meant that he wants to know how many commits on master in the last week, not have to count all of the commits? So a short-form summary report might work for that?

**Comment by aerickson14** [comment]
Ok, I can change it so that there is only one line per repository that is more of a summary to cut down on the noise.

**Comment by paulthorsteinson** [comment]
In regards to the desired output/use - Basically committing to master is a smell that we just want to check in on.  Can be innocuous like a version bump or even commits to robodev to change json which are fine, but could also be someone who has no reviewer and just pressed ahead.  Will allow us to ensure that we can find anywhere this happens and make sure the person has a reviewer.

**Comment by aerickson14** [comment]
All latest changes are now on the remote. Should be good to go if everyone is ok with the latest summary format.

**Comment by paulthorsteinson** [comment]
I'm ok with it for now.  Can always improve later if need be

**Pull request merged**
